serviceCenter/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_details'),
    path('add/<int:issue_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:issue_id>/',
         views.cart_remove,
         name='cart_remove')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serviceCenter/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('list_orders/',views.list_orders, name='list_orders')
]

serviceCenter/serviceCenter/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'serviceCenter'

urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('services.urls', namespace='services')),
     path('auth/', include('login.urls', namespace='login')),
     path('cart/', include('cart.urls', namespace='cart')),
     path('order/', include('order.urls', namespace='order')),
     path('statistic/', include('statistic.urls', namespace='statistic')),
     path('personal_account/',include('personal_account.urls',namespace= 'personal_account'))
]

serviceCenter/services/urls.py
from django.urls import path
from .import views


app_name = 'services'


urlpatterns = [
    path('', views.all_devices, name='home'),
    path('services', views.services, name="services"),
    path('create', views.create, name='create'),
    path('createIssue',views.create_issue,name='createIssue'),
    path('edit/<int:id>/',views.issue_edit,name='editIssue'),
    path('details/<int:id>/',views.detail,name='detail'),
    path('faq',views.faq,name='faq'),
    path('about_us',views.about_us,name='about_us'),
    path('news',views.news,name='news'),
    path('feedback',views.feed_back,name='feedback'),
    path('contacts',views.contacts,name='contacts'),
    path('trash',views.trash,name='trash'),
    path('promo_codes', views.promo_codes_view, name='promo_codes_view')
]

serviceCenter/cart/forms.py
from django import forms

Issue_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartIssueAddForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=Issue_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

serviceCenter/cart/views.py
from django.shortcuts import render
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartIssueAddForm
from services.models import Issue
# Create your views here.
@require_POST
def cart_add(request, issue_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("Net dostupa")

    cart = Cart(request)
    issue = get_object_or_404(Issue, id=issue_id)
    form = CartIssueAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(issue=issue,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_details')

def cart_remove(request, issue_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("Net dostupa")

    cart = Cart(request)
    book = get_object_or_404(Issue, id=issue_id)
    cart.remove(book)
    return redirect('cart:cart_details')

def cart_detail(request):
    if not request.user.is_authenticated:
        raise PermissionDenied("Net dostupa")
    cart = Cart(request)
    return render(request, 'cart/details.html', {'cart': cart})

serviceCenter/cart/templates/cart/details.html
<!DOCTYPE html>
{% load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title  %} {% endblock  %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
     <h1>Your shopping cart</h1>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Картинка</th>
                <th>Устройство</th>
                <th>Услуга</th>
                <th>Удалить</th>
                <th>Цена</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with issue=item.issue %}
                <tr>
                    <td>
                        <a href="{{ device.get_absolute_url }}">
                            <img src="
                                {% if device.image %}
                                    {{ device.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ issue.device_type }}</td>
                    <td>{{ issue.issue_type }}</td>
                    <td><a class="btn btn-danger" href="{% url 'cart:cart_remove' issue.id %}">Remove</a></td>
                    <td class="num">{{ item.price }}</td>
                    <td class="num">{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        </tbody>
    </table>

    <p class="text-right">
        <a href="{% url 'services:home' %}" class="btn btn-warning">Continue shopping</a>
        <a href="{% url 'order:order_create' %}" class="btn btn-warning">
            Checkout
        </a>
    </p>
</body>