serviceCenter/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_details'),
    path('add/<int:issue_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:issue_id>/',
         views.cart_remove,
         name='cart_remove')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serviceCenter/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

serviceCenter/serviceCenter/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'serviceCenter'

urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('services.urls', namespace='services')),
     path('auth/', include('login.urls', namespace='login')),
     path('cart/', include('cart.urls', namespace='cart')),
     path('order/', include('order.urls', namespace='order')),
     path('statistic/', include('statistic.urls', namespace='statistic')),
     path('personal_account/',include('personal_account.urls',namespace= 'personal_account'))
]

serviceCenter/login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .user_manager import CustomUserManager

class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=200,
                                  help_text='Enter first name')
    last_name = models.CharField(max_length=200,
                                 help_text='Enter last name')
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=50,
                                    help_text='Enter phone number')
    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email', 'date_of_birth', 'phone_number']

serviceCenter/login/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.core.validators import RegexValidator
from django import forms

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=200,
                                 help_text='Enter first name')
    last_name = forms.CharField(max_length=200,
                                help_text='Enter last name')
    date_of_birth = forms.DateField()
    phone_number = forms.CharField(max_length=50,
                                   help_text='Enter phone number',
                                   validators=[RegexValidator(
                                       regex=r'^(\+375 \(29\) [0-9]{3}-[0-9]{2}-[0-9]{2})$',
                                       message='Format +375 (29) XXX-XX-XX',
                                   )])

    class Meta:
        model = CustomUser
        fields = {'username', 'email', 'first_name',
                  'last_name', 'date_of_birth',
                  'phone_number', 'password1',
                  'password2'
                  }

serviceCenter/login/views.py
from django.views.generic.edit import FormView
from services.models import Client
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
import requests
from django.contrib.auth import logout
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import UserCreateForm

# Create your views here.

class RegisterFormView(FormView):
    form_class = UserCreateForm
    success_url = ''

    template_name = 'register.html'
    print(123)

    def form_valid(self, form) -> HttpResponse:

        form.save()

        Client.objects.create(first_name=form.cleaned_data['first_name'],
                              last_name=form.cleaned_data['last_name'],
                              date_of_birth=form.cleaned_data['date_of_birth'],
                              email=form.cleaned_data['email'],
                              phone_number=form.cleaned_data['phone_number']).save()

        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form) -> HttpResponse:
        return super(RegisterFormView, self).form_invalid(form)

class LoginFormView(FormView):
        form_class = AuthenticationForm

        template_name = 'login.html'

        quote = requests.get('https://favqs.com/api/qotd').json()

        def get(self, request):
            return render(request, 'login.html',
                          context={'form': self.form_class(), 'quote': self.quote['quote']['body']})

        success_url = '/'

        def form_valid(self, form) -> HttpResponse:
            self.user = form.get_user()

            login(self.request, self.user)
            return super(LoginFormView, self).form_valid(form)


class LogoutView(FormView):
    def get(self, request):
        logout(request)

        return HttpResponseRedirect('/')

serviceCenter/login/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Registration</title>
    </head>
    <body>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign in</button>
        </form>

    </body>
    <tail>
        <div class="bottom-right">
            <p>Quote for you: {{ quote }}</p>
        </div>
    </tail>
</html>

serviceCenter/login/templates/register.html
<!DOCTYPE html>
{% load static%}
<html>
    <head>
        <title>Registration</title>
        <link rel="stylesheet" href="{% static 'login/css/registration.css'%}"/>
    </head>
    <body>
        <form class="form-container" method="POST">
             {% csrf_token %}
            <div>
                <!-- Email Field -->
                <h3>Регистрация</h3>
                  <label for="id_email">Email:</label>
                  <input type="email" id="id_email" name="email" required>

                <!-- First Name Field -->
                <div class="">
                  <label for="id_first_name">First Name:</label>
                  <input type="text"  id="id_first_name" name="first_name" required>
                </div>

                <!-- Last Name Field -->
                <div class="">
                  <label for="id_last_name">Last Name:</label>
                  <input type="text"  id="id_last_name" name="last_name" required>
                </div>

                <!-- Date of Birth Field -->
                <div class="">
                  <label for="id_date_of_birth">Date of Birth:</label>
                  <input type="date"  id="id_date_of_birth" name="date_of_birth" disabled>
                </div>


                <!-- Phone Number Field -->
                <div class="">
                  <label for="id_phone_number">Phone Number:</label>
                  <input type="tel"  id="id_phone_number" name="phone_number">
                </div>

                <label>
                    <input type="radio" name="sex" value="male">
                    Male
                </label>
                <label>
                    <input type="radio" name="sex" value="female">
                    Female
                </label>

                <!-- Password Field -->
                <div class="">
                  <label for="id_password1">Password:</label>
                  <input type="password"  id="id_password1" name="password1" pattern=".{4,}" required>
                </div>

                <!-- Password Confirmation Field -->
                <div >
                  <label for="id_password2">Confirm Password:</label>
                  <input  type="password" class=" button-container" id="id_password2" name="password2" pattern=".{4,}" required>
                </div>
                <button type="submit">Register</button>
            </div>

        </form>
    </body>
</html>