serviceCenter/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_details'),
    path('add/<int:issue_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:issue_id>/',
         views.cart_remove,
         name='cart_remove')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serviceCenter/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

serviceCenter/personal_account/urls.py
from django.urls import path
from . import views

app_name = 'personal_account'

urlpatterns = [
    path('', views.personal_account, name='personal_account')
]

serviceCenter/serviceCenter/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'serviceCenter'

urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('services.urls', namespace='services')),
     path('auth/', include('login.urls', namespace='login')),
     path('cart/', include('cart.urls', namespace='cart')),
     path('order/', include('order.urls', namespace='order')),
     path('statistic/', include('statistic.urls', namespace='statistic')),
     path('personal_account/',include('personal_account.urls',namespace= 'personal_account'))
]

serviceCenter/services/urls.py
from django.urls import path
from .import views


app_name = 'services'


urlpatterns = [
    path('', views.all_devices, name='home'),
    path('services', views.services, name="services"),
    path('create', views.create, name='create'),
    path('createIssue',views.create_issue,name='createIssue'),
    path('edit/<int:id>/',views.issue_edit,name='editIssue'),
    path('details/<int:id>/',views.detail,name='detail'),
    path('faq',views.faq,name='faq'),
    path('about_us',views.about_us,name='about_us'),
    path('news',views.news,name='news'),
    path('feedback',views.feed_back,name='feedback'),
    path('contacts',views.contacts,name='contacts'),
    path('trash',views.trash,name='trash'),
    path('promo_codes', views.promo_codes_view, name='promo_codes_view')
]

serviceCenter/statistic/urls.py
from django.urls import path
from . import views

app_name = 'statistic'

urlpatterns = [

    path("history", views.user_order_history, name="history"),
    path("analyze", views.shop_analyzer, name="analyze")
]

serviceCenter/services/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

class Device_type(models.Model):

    # класс для типа товара, ноутбук, планшет, телефон, пк, наушники, и для них виды услуг из Issue
    name = models.CharField(max_length=100)

    image = models.ImageField(upload_to='static/services/img/', blank=True)

    def __str__(self):
        return self.name



class Issue(models.Model):

    # класс для услу к примеру чистка от пыли, замена термопасты, ремонт, замена экрана и т.д
    issue_type = models.CharField(max_length=100)

    price = models.DecimalField(max_digits=10,decimal_places=2)

    device_type = models.ForeignKey(Device_type
                                    , on_delete=models.CASCADE)

    count = models.DecimalField(max_digits=10,decimal_places=2,default=0)

    def get_absolute_url(self):
        return reverse('services:detail', args=[str(self.id)])
    def __str__(self):
        return self.issue_type



class Client(models.Model):

    first_name = models.CharField(max_length=200)

    last_name = models.CharField(max_length=200)

    date_of_birth = models.DateField()

    email = models.EmailField()

    phone_number = models.CharField(max_length=50,)

    image = models.ImageField(upload_to='static/services/img/', blank=True)

    def __str__(self):
        return self.email

class News(models.Model):
    image = models.ImageField(upload_to='static/services/img/', blank=True)
    name = models.CharField(null=False, max_length=300)
    description = models.CharField(null=False, max_length=80)
    full_text = models.TextField(null=False, max_length=1000)
    resource = models.CharField(max_length=300, null=False,default="")

    def __str__(self):
        return self.name

class FeedBack(models.Model):
    client = models.ForeignKey(Client
                                    , on_delete=models.CASCADE)
    text = models.TextField(null = False, max_length=350)

    mark = models.DecimalField(null = False,decimal_places=0,max_digits=1)

    image = models.FileField(upload_to='static/services/img/', blank=True)

    time = models.TimeField(null= False)

class Stuff(models.Model):
    first_name = models.CharField(max_length=200)

    last_name = models.CharField(max_length=200)

    date_of_birth = models.DateField()

    email = models.EmailField()

    phone_number = models.CharField(max_length=50, )

    image = models.ImageField(upload_to='static/services/img/', blank=True)

    job_description = models.CharField(max_length=1000)



class BannerChangeTimer(models.Model):
    milliseconds = models.IntegerField(
        validators=[MinValueValidator(1000), MaxValueValidator(30000)])
    

class PromoCode(models.Model):
    promo_code = models.IntegerField(unique=True,
                                     validators=[MinValueValidator(1), MaxValueValidator(10000)])
    name = models.CharField(max_length=100)
    discount_size = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)])
    active = models.BooleanField(default=True)

serviceCenter/services/forms.py
from django import forms
from .models import Device_type,Issue,FeedBack
class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device_type
        fields = ['name', 'image']

        widgets = {
            "name": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'название устройства',
            }),
            "image": forms.FileInput(attrs={
                'class': 'form-control',
                'placeholder': 'картинка устройства'
            }),

        }

class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['issue_type', 'price', 'device_type']

        widgets = {
            "issue_type": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'название устройства',
            }),
            "price": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'название устройства',
            }),
            "device_type": forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'название устройства',
            }),

        }

class FeedBackForm(forms.ModelForm):
    class Meta:
        model = FeedBack
        fields = ['client', 'text', 'mark','time']

        widgets = {
            "client": forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Укажите ваше имя',
            }),
            "text": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'введите ваш отзыв',
            }),

            "mark": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'оцените нас от 1 до 5',
            }),
            "time": forms.TimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Укажите дату отправки отзыва',
            }),
        }

serviceCenter/services/views.py
from django.shortcuts import render
from .models import Device_type, Issue,News,FeedBack, Stuff,BannerChangeTimer,PromoCode
from .forms import DeviceForm, IssueForm, FeedBackForm
from django.views.generic import ListView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound
from cart.forms import CartIssueAddForm
from django.contrib.auth import logout
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
import requests

# def index(request):
#     return render(request, 'services/mainPage.html')


def services(request):
    devices = Device_type.objects.all()

    return render(request, 'services/ourServices.html', {'devices': devices})


def all_devices(request):
    device_types = Device_type.objects.all()
    news = News.objects.all()

    if (request.method == "POST" and request.user.is_superuser):
            time = BannerChangeTimer.objects.get(id=1)
            time.milliseconds = request.POST.get('milliseconds')
            time.save()
    
    time = BannerChangeTimer.objects.get(id=1)
    quote = requests.get('https://favqs.com/api/qotd').json()

    return render(request, 'services/mainPage.html',
                  {'Device_type': device_types,
                   'News': news,
                   'milliseconds': time.milliseconds,
                   'quote': quote['quote']['body']})

def create(request):

    if request.method == 'POST':
        form = DeviceForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            error = 'MISTAKE'

    form = DeviceForm()

    data = {
        'form': form,

    }
    return render(request, 'services/create.html',data)


def create_issue(request):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")

    if request.method == 'POST':
        form = IssueForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            error = 'MISTAKE'

    form = IssueForm()

    data = {
        'form': form,

    }
    return render(request, 'services/create_issue.html', data)

def issue_edit(request,id):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")
    try:
        issue = Issue.objects.get(id=id) # problem because id - device-id

        form = IssueForm(initial={'issue_type': issue.issue_type, 'price': issue.price,
                                 'device_type': issue.device_type})

        if request.method == "POST":
            issue.title = request.POST.get('issue_type')
            print(request.POST.get('title'))
            issue.price = request.POST.get('price')
            issue.device_type = Device_type.objects.get(id=request.POST.get('device_type'))

            issue.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "services/edit.html", {"issue": issue, 'form': form})
    except issue.DoesNotExist:
        return HttpResponseNotFound("<h2>book not found</h2>")


def detail(request, id):
    device = Device_type.objects.get(id=id)
    issues = Issue.objects.filter(device_type__name=device.name)
    cart_form = CartIssueAddForm()

    sort_t = request.GET.get('sort')

    if (str(sort_t) == 'ascending'):
        issues = issues.order_by('price')
    elif (str(sort_t) == 'descending'):
        issues = issues.order_by('-price')


    data = {
        'device': device,
        'issues': issues,
        'cart_form':cart_form
    }
    return render(request, 'services/details.html', data)

def news(request):
    return render(request, "services/news.html", {"news": News.objects.all()})

def faq(request):
    return render(request, "services/faq.html")

def about_us(request):
    return  render(request,"services/about_us.html")

def contacts(request):
    workers = Stuff.objects.all()
    return render(request,"services/contacts.html",{'workers': workers})

def feed_back(request):
    if request.method == 'POST':
        form = FeedBackForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            error = 'MISTAKE'

    feed_backs = FeedBack.objects.all()

    form = FeedBackForm(request.POST)

    data = {
        'form': form,
        'feedbacks': feed_backs
    }
    return render(request, 'services/feedback.html', data)

def trash(request):
    return render(request,"services/Trash.html")

def promo_codes_view(request):
    promo_codes = PromoCode.objects.all()
    return render(request, "services/promo_codes.html", {'promo_codes': promo_codes})

serviceCenter/services/templates/services/Trash.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'services/css/trash.css'%}"/>

</head>
<body>
    <a href="https://ria.ru/">Ссылка оканчивающаясяя на .ru</a>
    <br>
    <a href="https://www.belta.by/">Ссылка оканчивающаясяя на .by</a>
    <br>
    <a href="https://www.youtube.com/">Ссылка в которой есть ютуб</a>
    <br>
    <a href="https://www.google.com/">Ссылка оканчивающаясяя на другое</a>

    <ul>
        <li>Item 1</li>
        <li>Item 2</li>
        <li>Item 3</li>
        <li>Item 4</li>
        <li>Item 5</li>
    </ul>

    <p>
        Я хочу работать в фабрике инноваций и технологий, потому что вы современная и растущая компания,
        с обширным стеком технологий и с работой на огромном числе доменов. Много моих знакомых работало
        у вас и хорошо отзывались о внутреннем устройстве компании, коллективе и корпоративной культуре.
        Так же я люблю английский язык и хочу развивать его параллельно работая.
    </p>

    <p class="temp_text">
        Я хочу работать в фабрике инноваций и технологий, потому что вы современная и растущая компания,
        с обширным стеком технологий и с работой на огромном числе доменов. Много моих знакомых работало
        у вас и хорошо отзывались о внутреннем устройстве компании, коллективе и корпоративной культуре.
        Так же я люблю английский язык и хочу развивать его параллельно работая.
    </p>

    <div>
        <video controls src="{% static 'video/video.mp4' %}"></video>
    </div>

    <div>
        <audio controls src="{% static 'audio/audio.mp3' %}"></audio>
    </div>

    <section>
        <div class="circular-image">
            <img src="{% static 'services/img/banner.jpg' %}" alt="Banner1">
        </div>
        <div class="circular-image rotating">
            <img src="{% static 'services/img/banner.jpg' %}" alt="Banner2">
        </div>
        <div class="circular-image">
            <img src="{% static '/services/img/banner.jpg' %}" alt="Banner3">
        </div>
    </section>

    <div id="box"></div>
</body>
</html>

serviceCenter/services/templates/services/about_us.html
{% extends "services/layout.html"  %}
{% load static%}

{% block name  %}
    <title></title>
{% endblock  %}

{% block css  %}
    <link rel="stylesheet" href="{% static 'services/css/about_us.css'%}"/>
{% endblock  %}

{% block content  %}
<figure>
    <img src="">
    <a href="#video"><li>Olezhka service</li></a>
</figure>
<section>
    <article class="temp_text">
     Welcome to [Company Name], your trusted partner in the world of technology.
        In today's fast-paced digital landscape, where businesses and individuals
        rely heavily on computers and technology, having a reliable and efficient
        computer service company by your side is essential. At [Company Name], we
        understand the critical role that technology plays in your life and work,
        and we are here to ensure that it functions seamlessly.
    </article>
    <br>
    <hr>
    <br>
    <article class="temp_text">
        Join us on a journey where technology meets reliability, where your computer
        needs are met with expertise and dedication. Discover the difference with [Company Name],
        your trusted partner in computer services.
    </article>
</section>



<div class="temp_text">
    <h3>Our proud</h3>
    <ol>
        <li>We help to repair 18237 laptops, headphones, phones and other devices</li>

        <li>We got 87% of 5 star ..., 11% of 4 star..., and only 2 percent of 3 and less stars...</li>

        <li>We are working in 47 countries and 4 continents.</li>

        <li>And other facinating facts about us</li>

    </ol>
</div>

<div class="certificate">
    <h3>Sertificate</h3>
    <p class="certificate-title">Certificate of Service</p>
        <p class="cetificate">This is to certify that</p>
        <h1>Olezhka Service Center</h1>
        <p>has successfully completed the requirements and standards set forth for</p>
        <h2>Service Center Excellence</h2>
        <p>awarded on this day</p>
        <p><strong>September 23, 2023</strong></p>
        <p>at</p>
        <p><strong>Our Certification Organization</strong></p>
        <p>Sign_____________________________</p>
</div>

<section>
    <form method="POST" id="form">
        {% csrf_token %}

        <label>
            <input type="checkbox" name="font-size-checkbox" id="font-size-checkbox" onchange="toggleFontSize()"> Change
            font size:
        </label>
        <br>

        <div id="font-size-field" style="display: none;">
            <input type="range" id="fontSize" name="fontSize" min="12" max="24" step="1">
        </div>
        <br>

        <label>
            <input type="checkbox" name="text-color-checkbox" id="text-color-checkbox" onchange="toggleTextColor()">
            Change text colour:
        </label>
        <br>

        <div id="text-color-field" style="display: none;">
            <input type="color" id="textColor" name="textColor">
        </div>
        <br>

        <label>
            <input type="checkbox" name="background-color-checkbox" id="background-color-checkbox"
                onchange="toggleBackgroundColor()"> Change background colour:
        </label>
        <br>

        <div id="background-color-field" style="display: none;">
            <input type="color" id="backgroundColor" name="backgroundColor">
        </div>
        <br>

        <input type="submit">
    </form>

</section>

<h3 class="h3 mt-3 m-lg-4 mb-3">History</h3>
<ul class="list-group list-group-flush m-lg-5">

    <li class="temp_text">
        1920s - Founding Years:
        TechCare Solutions had its humble beginnings in the early 1920s when a group of skilled radio technicians in a
        small workshop decided to combine their expertise to offer repair services for the then-emerging technology of
        radios. They started as a small, family-owned business known as "Smith & Sons Radio Repair."

    </li>
    <li class="temp_text">
        1930s - Transition to Electronics:
        As technology advanced, so did the services offered by the company. In the 1930s, they expanded their offerings
        to include the repair of early television sets, becoming one of the first businesses in their region to do so.

    </li>
    <li class="temp_text">
        1950s - Post-War Boom:
        The post-World War II era brought an explosion of consumer electronics. TechCare Solutions capitalized on this
        boom by opening multiple service centers throughout the region. They also began offering maintenance contracts
        to businesses, providing routine check-ups and repairs for their electronic equipment.

    </li>
    <li class="temp_text">
        2000: Embracing technological advancements, [Company Name] launches its first e-commerce website, allowing
        customers
        to browse and purchase toys from the comfort of their homes. The online store expands the company's reach beyond
        the
        local community, attracting toy enthusiasts from all over the country.

    </li>
    <li class="temp_text">
        1970s - The Computer Age:
        With the advent of personal computers in the 1970s, TechCare Solutions saw an opportunity to expand into a new market.
        They rebranded themselves as "TechCare Solutions" and established a dedicated division for computer repairs and maintenance.
        During this period, they gained contracts with several local businesses, schools, and government agencies.

    </li>
    <li class="temp_text">
        1990s - Digital Revolution:
        The 1990s marked a period of significant growth for TechCare Solutions. They embraced the digital revolution by offering
        repair services for a wide range of digital devices, including laptops, mobile phones, and gaming consoles. They also
        launched their website, allowing customers to schedule appointments online and access troubleshooting guides.
    </li>
    <li class="temp_text">
        2000s - Global Expansion:
        As technology became more interconnected, TechCare Solutions expanded globally, opening service centers in several countries.
        They partnered with major technology companies to provide authorized repair services for their products, solidifying their
        reputation as a trusted service provider.

    </li>
    <li class="temp_text">
        In response to growing environmental concerns, TechCare Solutions adopted eco-friendly practices. They introduced a recycling program for electronic waste and began offering repair services for sustainable energy solutions, such as solar panels and electric vehicle charging stations.

        2020s - Online and Remote Support:
        The COVID-19 pandemic accelerated the company's move towards online and remote support options. They invested in virtual diagnostic tools and remote troubleshooting, allowing customers to receive assistance from the comfort of their homes.

        Future Prospects:

    </li>

</ul>

<div itemscope itemtype="http://schema.org/VideoObject">
    <iframe id="video" width="560" height="315" src="https://www.youtube.com/embed/w0xx477aeys?si=ECYjiM3sCH3uMS9M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <meta itemprop="name" content="Видео Рамзи">
</div>

<script src="{% static 'services/js/about_us.js' %}" defer></script>
{% endblock  %}

serviceCenter/services/templates/services/contacts.html
{% extends "services/layout.html"  %}
{% load static%}

{% block name  %}
    <title>Contacts</title>
{% endblock  %}

{% block css  %}
    <link rel="stylesheet" href="{% static 'services/css/contacts.css'%}"/>
{% endblock  %}

{% block content  %}
  <h2>Contacts</h2>

  <div style="width: 200px, padding: 50px">


    <section class="flex">
      {% for worker in workers %}
    <section itemscope itemtype="https://schema.org/Person"><img src={{worker.image.url}} alt="Employee Photo"
            height="200" width="200">
        <ul>
            <li itemprop="name">{{ worker.first_name }} {{ worker.last_name }}</li>
            <li itemprop="description"><small>Responsibilities: {{ worker.description }}</small></li>
            <li itemprop="telephone"><small>Phone: {{ worker.phone_number }} </small></li>
            <li itemprop="email"><small>Email: <a href="mailto:{{ worker.email }}">{{ worker.email }}</a></small></li>
        </ul>
    </section>
    {% endfor %}
    </section>
  </div>



{% endblock  %}

serviceCenter/services/templates/services/create.html
{% extends "services/layout.html"  %}
{% load static%}

{% block name  %}
    <h1>Добавление нового устройства</h1>
{% endblock  %}

{% block css  %}
    <link rel="stylesheet" href="{% static 'services/css/layout.css'%}"/>
{% endblock  %}

{% block content  %}
    <div class="features">

        <h1>сама формочка для добавления</h1>
      <form method="post">
          {% csrf_token %}
          {{ form }}
          <button class="btn btn-success m-10"  type="submit">Добавить</button>
      </form>
    </div>


{% endblock  %}


{% block title  %}
    <h1>Ремонт ноутбуков</h1>
{% endblock  %}

serviceCenter/services/templates/services/create_issue.html
{% extends "services/layout.html"  %}
{% load static%}

{% block name  %}
    <h1>Добавление нового устройства</h1>
{% endblock  %}

{% block css  %}
    <link rel="stylesheet" href="{% static 'services/css/layout.css'%}"/>
{% endblock  %}

{% block content  %}
    <div class="features">

        <h1>сама формочка для добавления</h1>
      <form method="post">
          {% csrf_token %}
          {{ form }}
          <button class="btn btn-success m-10"  type="submit">Добавить</button>
      </form>
    </div>


{% endblock  %}


{% block title  %}
    <h1>Ремонт ноутбуков</h1>
{% endblock  %}

serviceCenter/services/templates/services/details.html
<!DOCTYPE html>
{% load static%}
    <html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="{% static 'services/css/layout.css'%}"/>
        <link rel="stylesheet" href="{% static 'services/css/details.css'%}"/>
        <title>Edit</title>
    </head>
    <body>
             <form action="{{ request.get_full_path }}" method="get">
                <button class="btn btn-primary m-3" type="submit" name="sort" value="ascending">Сортировать по возрастанию</button>
                <button class="btn btn-primary m-3" type="submit" name="sort" value="descending">Сортировать по убыванию</button>
            </form>

            <h5>{{ device.name }}</h5>>
            <table class="">
                 <thead class="">
                    <tr>
                        <th>Вид услуги</th> <th>цена</th> <th></th> <th></th>
                    </tr>
                </thead>

                <tbody>
                     {%for issue in issues%}
                        <tr>
                            <td>{{issue.issue_type}}</td> <td>{{issue.price}}</td>
                            <td rowspan="2"><a href="{% url 'services:editIssue' issue.id %}"><button class="btn btn-warning">изменить</button></a></td>
                            {% if user.is_staff %}
                            <td rowspan="2">
                                <a href="{% url  'cart:cart_add' issue.id %}"><button class="btn btn-warning">добавить</button></a>
                                <form action="{% url 'cart:cart_add' issue.id %}" method="post">
                                    {{ cart_form }}
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-warning" value="Add to cart">
                                </form>
                            </td>
                            {% endif %}
                        </tr>
                    {% empty %}

                    {% endfor %}
                </tbody>

            </table>


    </body>
    </html>

serviceCenter/services/templates/services/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Title</title>
</head>


<body>
      <div class="features">

        <h1>сама формочка для добавления</h1>
          <form method="post">
              {% csrf_token %}
              {{ form }}
              <button class="btn btn-success m-10"  type="submit">Добавить</button>
          </form>
    </div>
</body>
</html>

serviceCenter/services/templates/services/faq.html
{% extends "services/layout.html"  %}

{% block name  %}
    <title>FAQ</title>
{% endblock  %}

{% block content  %}
<details>
  <summary>How connect with us ?</summary>
  you can use the following:
  <ol>
    <li>gmail</li>
    <li>phone</li>
    <li>other</li>
  </ol>
</details>



<details>
  <summary>Another intresting question ?</summary>
 Another intresting answer.
</details>


{% endblock  %}

serviceCenter/services/templates/services/feedback.html
{% extends "services/layout.html"  %}
{% load static%}

{% block name  %}
    <title>Feedback</title>
{% endblock  %}

{% block css  %}

{% endblock  %}

{% block content  %}
<div>
     <form method="post">
          {% csrf_token %}
          {{ form }}
          <button type="submit">Добавить отзыв</button>
      </form>
</div>

<div>
    {% for feedback in feedbacks%}
    <article>
        <h3>{{feedback.client.name}}</h3>
        <h3>Оценка от 1 до 5: {{feedback.mark}} </h3>

        <br>
        
        <pre>
            {{ feedback.text }}
        </pre>
        <hr>

    </article>
    {%endfor%}
</div>
{% endblock  %}

serviceCenter/services/templates/services/layout.html
<!DOCTYPE html>
{% load static%}

<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="serviceCenter",
            content="service center - this is the way to work with effective hardware">
    <title>{% block title  %} {% endblock  %}</title>

    {% block css  %}
    {% endblock  %}

    <link rel="stylesheet" href="{% static 'services/css/layout.css'%}"/>
    <link rel="shortcut icon" href="{% static 'services/img/digital_logo.ico' %}" type="image/x-icon">
    <script src="{% static 'services/js/timer.js' %}" defer></script>      
</head>


<body>
        <nav>

             {% if user.is_authenticated %}
                    |{{ user.username }}|
                    <a href="{% url 'login:logout' %}">Сделать больно и покинуть чат</a>
                    {% else %}
                    <a href="{% url 'login:login' %}">Войти</a>
                    <a href="{% url 'login:register' %}">Зарегистрироваться</a>
                    {% endif %}

    </nav>
    <aside>
        <img class="image-transform"  src="{% static 'services/img/logo.jpg' %}" height="50" width="70"  alt="logo">
        <span class="logo"> пелемешки от Олежки</span>
        <div>
            <q>{{quote}}</q>
        </div>
        <hr>
        <div id="countdown"></div>
        <hr>
        <h3>Навигация</h3>
        <ul>
            <a href="{% url 'personal_account:personal_account' %}"><li>Личный аккаунт</li></a>
            <a href="{% url 'services:promo_codes_view' %}"><li>Купоны</li></a>
            <a href="{% url 'services:services' %}"><li>Наши услуги</li></a>
            <a href="{% url 'services:contacts'%}"><li>Контакты</li></a>
            <a href="{% url 'services:about_us'%}"><li>О нас</li></a>
            <a href="{% url 'services:feedback'%}"><li>Отзывы</li></a>
            {% if user.is_staff %}
            <a href="{% url 'services:create'%}"><li>Добавить устройство</li></a>
            <a href="{% url 'services:createIssue' %}"><li>Добавить услугу</li></a>
            <a href="{% url 'statistic:history' %}"><li>History</li></a>
            <a href="{% url 'statistic:analyze' %}"><li>Analyze</li></a>
            <a href="{% url 'services:trash' %}"><li>Эксперементы</li></a>
            {% endif %}

        </ul>
         <div class="cart">
            {%if user.is_authenticated%}
             <a href="{% url 'cart:cart_details' %}"><li>Корзина</li></a>
            {%endif%}
        </div>

        <pre>
            <code>
            while(alive){
                write_html();
                if(you_died()){
                    reborn();
                }
            }

        </code>
        </pre>


    </aside>
    <main>

        {% block content  %}
        {% endblock  %}
    </main>
    
</body>

</html>

serviceCenter/services/templates/services/news.html
{% extends "services/layout.html"  %}

{% block name  %}
    <title>News</title>
{% endblock  %}

{% block content  %}
<div>
    {% for n in news %}
    <article>
        <h2>{{n.name}}</h2>
        <br>
        <p class="clip">{{n.description}}</p>
        <img src="{{n.img_url}}">
        <br>
        <details>
            <summary>Continue</summary>
            {{n.full_text }}
        </details>
    </article>
</div>
{% endblock  %}